// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM2dQnbCbQ5qe7V9Xqh87HQKLgP2hF51M',
    appId: '1:562079004596:web:8eaf420326b2b3146fe4e1',
    messagingSenderId: '562079004596',
    projectId: 'ostad-94a28',
    authDomain: 'ostad-94a28.firebaseapp.com',
    storageBucket: 'ostad-94a28.appspot.com',
    measurementId: 'G-ZNK38RLK5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1E8wiDw6gpUETqz5IijuE1WCxn9xerlQ',
    appId: '1:562079004596:android:adb1e0d5d14fbcf96fe4e1',
    messagingSenderId: '562079004596',
    projectId: 'ostad-94a28',
    storageBucket: 'ostad-94a28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLCBVTBeZ6uAZ9ssPArC8CaZggIj6CK2k',
    appId: '1:562079004596:ios:8700f93cba55133f6fe4e1',
    messagingSenderId: '562079004596',
    projectId: 'ostad-94a28',
    storageBucket: 'ostad-94a28.appspot.com',
    iosBundleId: 'com.example.module16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLCBVTBeZ6uAZ9ssPArC8CaZggIj6CK2k',
    appId: '1:562079004596:ios:4e76c9f6155ce8336fe4e1',
    messagingSenderId: '562079004596',
    projectId: 'ostad-94a28',
    storageBucket: 'ostad-94a28.appspot.com',
    iosBundleId: 'com.example.module16.RunnerTests',
  );
}
